const initial = () => ({
  teams: [],
  rounds: [{name:'Round 1',q:0,time:'10:00',status:'Locked',n:1},
    {name:'Round 2',q:0,time:'10:00',status:'Locked',n:2},
    {name:'Round 3',q:0,time:'10:00',status:'Locked',n:3},
    {name:'Round 4',q:0,time:'10:00',status:'Locked',n:4}],
  running:true, leaderboard:true, feedback:'after tournament', quizName:'QUIZ MASTER', duration:10,
  points:10, speedBonus:0, qcount:0, passwords:{}, roundAccess:{}, readyByRound:{}, verifiedRounds:{}, answers:[], questions:[], projectedQuestionId:null, phase:'admin', tab:'Overview'
});

const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const fail = (status,error) => json({error},status);
const csvCell = value => `"${String(value??'').replaceAll('"','""').replace(/[\r\n]/g,' ')}"`;
async function getState(env){
  await env.DB.prepare('INSERT OR IGNORE INTO app_state (id, body, version) VALUES (1, ?, 1)').bind(JSON.stringify(initial())).run();
  const row=await env.DB.prepare('SELECT body, version FROM app_state WHERE id=1').first();
  return {state:JSON.parse(row.body),version:row.version};
}
async function changeState(env, change){
  for(let i=0;i<8;i++){
    const {state,version}=await getState(env);const result=await change(state);
    const saved=await env.DB.prepare('UPDATE app_state SET body=?, version=version+1 WHERE id=1 AND version=?').bind(JSON.stringify(state),version).run();
    if(saved.meta.changes===1)return result;
  }
  throw new Error('The quiz is busy. Please try again.');
}
function normalizedQuestions(s){return (s.questions||[]).map((q,i)=>{const round=Number(q.round||String(q[0]||'').match(/\d+/)?.[0]||1),cfg=(s.rounds||[]).find(r=>r.n===round);return {id:String(q.id||`r${round}-q${i+1}`),round,text:q.text||q[1]||'',options:Array.isArray(q.options)?q.options:(Array.isArray(q)?q.slice(4,8).filter(Boolean):[]),answer:q.answer||q[2]||'',points:Number(q.points??q[4]??cfg?.points??s.points??10),type:q.type||((q.options||[]).length?'multiple-choice':'typed'),mediaUrl:q.mediaUrl||'',mediaType:q.mediaType||''}})}
function isComplete(s){const total=(s.rounds||[]).length;return total>0&&(s.teams||[]).length>0&&s.teams.every(t=>Number((t.progress||'0/0').split('/')[0])>=total)}
function readyCount(s,n){const set=new Set((s.readyByRound||{})[String(n)]||[]);return (s.teams||[]).filter(t=>set.has(t.code)).length}
function safeState(s){const done=isComplete(s),qs=normalizedQuestions(s),teams=s.teams||[],active=(s.rounds||[]).find(r=>r.active),ready=active?readyCount(s,active.n):0,allReady=!!active&&teams.length>0&&ready>=teams.length,projected=qs.find(q=>q.id===String(s.projectedQuestionId)),canShow=!!projected&&!!active&&active.n===projected.round&&allReady&&!done;return {quizName:s.quizName,running:s.running,leaderboard:s.leaderboard,rounds:(s.rounds||[]).map(({name,q,time,status,n,active,ended,deadlineAt,passwordRequired})=>({name,q,time,status,n,active,ended,deadlineAt,passwordRequired:passwordRequired!==false,readyCount:readyCount(s,n),allReady:teams.length>0&&readyCount(s,n)>=teams.length})),teams:teams.map(({name,points,progress,status,logo,logoColor})=>({name,points,progress,status,logo,logoColor})),allTeamsComplete:done,allTeamsReady:allReady,readyCount:ready,teamCount:teams.length,projectedQuestion:canShow?{id:projected.id,round:projected.round,text:projected.text,options:projected.options,answer:null,points:projected.points,mediaUrl:projected.mediaUrl,mediaType:projected.mediaType}:null,finalQuestions:done?qs.map(({id,round,text,options,answer,points,mediaUrl,mediaType})=>({id,round,text,options,answer,points,mediaUrl,mediaType})):[],updatedAt:Date.now()};}
function expireRound(s,r){if(r?.active&&r.deadlineAt&&Date.now()>=r.deadlineAt){r.active=false;r.ended=true;r.status='Completed';return true}return false}
function durationMs(r){const p=String(r?.time||'10:00').split(':').map(Number);return ((p.length>1?(p[0]*60+p[1]):p[0]*60)||600)*1000}
async function syncExpired(env){const {state}=await getState(env);if(!(state.rounds||[]).some(r=>r.active&&r.deadlineAt&&Date.now()>=r.deadlineAt))return;await changeState(env,s=>{for(const r of s.rounds||[]){if(r.active&&r.deadlineAt&&Date.now()>=r.deadlineAt){r.active=false;r.ended=true;r.status='Completed';for(const t of s.teams||[]){const p=Number((t.progress||'0/0').split('/')[0])||0;if(p<r.n){t.progress=`${r.n}/${s.rounds.length}`;t.status=r.n>=s.rounds.length?'Complete':`In round ${r.n+1}`}}}}return null})}
async function token(req,env,kind){const value=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!value)return null;const row=await env.DB.prepare('SELECT kind, team_code, expires FROM sessions WHERE token=?').bind(value).first();if(!row||row.kind!==kind||row.expires<Date.now())return null;return {value,code:row.team_code};}
function makeToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function body(req){try{return await req.json()}catch{return null}}
async function handleApi(req,env,url){
 const p=url.pathname,m=req.method;
 if(m==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'Content-Type,Authorization','access-control-allow-methods':'GET,POST,PUT,OPTIONS'}});
 if(m==='POST'&&p==='/api/admin/login'){
   const b=await body(req);if(!b||typeof b.password!=='string'||b.password!==env.ADMIN_PASSWORD)return fail(401,'Invalid admin password');
   const t=makeToken();await env.DB.prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()).run();await env.DB.prepare('INSERT INTO sessions(token,kind,team_code,expires) VALUES(?,?,?,?)').bind(t,'admin','',Date.now()+12*60*60*1000).run();return json({token:t,expiresIn:43200});
 }
 if(m==='POST'&&p==='/api/team/login'){
   const b=await body(req),code=String(b?.code||'').trim().toUpperCase(),{state}=await getState(env),team=(state.teams||[]).find(t=>t.code===code);if(!team)return fail(401,'Team code not found');
   const t=makeToken();await env.DB.prepare('INSERT INTO sessions(token,kind,team_code,expires) VALUES(?,?,?,?)').bind(t,'team',code,Date.now()+24*60*60*1000).run();return json({token:t,team:{name:team.name,code:team.code,progress:team.progress,logo:team.logo,logoColor:team.logoColor},state:safeState(state)});
 }
 if(m==='GET'&&p==='/api/public/state'){await syncExpired(env);return json(safeState((await getState(env)).state));}
 if(m==='POST'&&p==='/api/admin/media'){
   if(!await token(req,env,'admin'))return fail(401,'Admin login required');
   const form=await req.formData(),file=form.get('file'),allowed=['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm'];if(!file||typeof file.arrayBuffer!=='function')return fail(400,'Choose an image or video first');if(!allowed.includes(file.type))return fail(415,'Use JPG, PNG, WEBP, GIF, MP4 or WEBM');if(file.size>1800000)return fail(413,'For free Cloudflare storage, uploads must be 1.8 MB or smaller. Add a video link for larger clips.');
   await env.DB.prepare('CREATE TABLE IF NOT EXISTS question_media (id TEXT PRIMARY KEY, mime_type TEXT NOT NULL, data BLOB NOT NULL, created_at TEXT NOT NULL)').run();const id=crypto.randomUUID(),data=new Uint8Array(await file.arrayBuffer());await env.DB.prepare('INSERT INTO question_media (id,mime_type,data,created_at) VALUES(?,?,?,?)').bind(id,file.type,data,new Date().toISOString()).run();return json({url:`/media/${id}`,type:file.type,name:file.name});
 }
 if(m==='POST'&&p==='/api/team/ready'){
   const ses=await token(req,env,'team');if(!ses)return fail(401,'Team login required');const b=await body(req),n=Number(b?.round);
   try{const result=await changeState(env,s=>{const r=s.rounds.find(x=>x.n===n),team=s.teams.find(x=>x.code===ses.code),progress=Number((team?.progress||'0/0').split('/')[0])||0;if(!s.running||!r?.active||progress!==n-1)throw Object.assign(Error('This round is not open for your team'),{status:409});s.readyByRound=s.readyByRound||{};const ready=s.readyByRound[String(n)]||[];if(!ready.includes(ses.code))ready.push(ses.code);s.readyByRound[String(n)]=ready;return {ok:true,ready:true,allReady:s.teams.length>0&&readyCount(s,n)>=s.teams.length,readyCount:readyCount(s,n),teamCount:s.teams.length}});return json(result)}catch(e){if(e.status)return fail(e.status,e.message);throw e}
 }
 if(m==='GET'&&p==='/api/admin/state'){if(!await token(req,env,'admin'))return fail(401,'Admin login required');await syncExpired(env);return json((await getState(env)).state)}
 if(m==='PUT'&&p==='/api/admin/state'){
   if(!await token(req,env,'admin'))return fail(401,'Admin login required');const s=await body(req);if(!s||!Array.isArray(s.teams)||!Array.isArray(s.rounds))return fail(400,'Invalid tournament state');
   await changeState(env,old=>{const roundCountChanged=(old.rounds||[]).length!==s.rounds.length;for(const team of s.teams){const saved=old.teams.find(t=>t.code===team.code);if(saved){team.points=Number(saved.points)||0;team.speed=Number(saved.speed)||0;if(!roundCountChanged){team.progress=saved.progress;team.status=saved.status}}}const before=(old.rounds||[]).find(r=>r.active),after=(s.rounds||[]).find(r=>r.active);s.answers=old.answers||[];if(before?.n!==after?.n){s.readyByRound={...(old.readyByRound||{})};if(after)s.readyByRound[String(after.n)]=[];s.verifiedRounds=Object.fromEntries(Object.entries(old.verifiedRounds||{}).filter(([key])=>!after||!key.startsWith(`${after.n}-`)))}else{s.readyByRound=old.readyByRound||s.readyByRound||{};s.verifiedRounds=old.verifiedRounds||s.verifiedRounds||{}}Object.assign(old,s);return null});return json({ok:true,updatedAt:Date.now()});
 }
 if(m==='POST'&&p==='/api/team/verify-round'){
   const ses=await token(req,env,'team');if(!ses)return fail(401,'Enter your team login code first');const b=await body(req),n=Number(b?.round);
   try{const result=await changeState(env,s=>{const r=(s.rounds||[]).find(x=>x.n===n),team=(s.teams||[]).find(t=>t.code===ses.code),progress=Number((team?.progress||'0/0').split('/')[0])||0,direct=!!s.roundAccess?.[`${n}-${ses.code}`]||r?.passwordRequired===false;if(expireRound(s,r))throw Object.assign(Error('This round is closed'),{status:409});if(!s.running||!r?.active)throw Object.assign(Error('This round is not open'),{status:409});if(!team||progress!==n-1)throw Object.assign(Error('Finish the previous round before starting this one'),{status:409});if(!(s.readyByRound?.[String(n)]||[]).includes(ses.code))throw Object.assign(Error('Mark your team ready before entering'),{status:409});const expected=s.passwords?.[`${n}-${ses.code}`];if(n>1&&!direct&&(!expected||String(b?.password||'').trim().toUpperCase()!==expected))throw Object.assign(Error('Incorrect round password'),{status:401});const questions=normalizedQuestions(s).filter(q=>q.round===n);if(!questions.length)throw Object.assign(Error('The host has not added questions for this round yet'),{status:409});s.verifiedRounds=s.verifiedRounds||{};s.verifiedRounds[`${n}-${ses.code}`]=true;return {round:{name:r.name,n:r.n,questions:questions.length,time:r.time,deadlineAt:r.deadlineAt},questions:questions.map(({id,text,options,points,type,mediaUrl,mediaType})=>({id,text,options,points,type,mediaUrl,mediaType}))}});return json({ok:true,...result})}catch(e){if(e.status)return fail(e.status,e.message);throw e}
 }
 if(m==='GET'&&p==='/api/team/state'){
   const ses=await token(req,env,'team');if(!ses)return fail(401,'Team login required');await syncExpired(env);const {state:s}=await getState(env),t=s.teams.find(x=>x.code===ses.code),rows=(s.answers||[]).filter(a=>a.team_code===ses.code).sort((a,b)=>a.round_no-b.round_no||a.question_id.localeCompare(b.question_id)),progress=Number((t?.progress||'0/0').split('/')[0])||0,reveal=progress>=s.rounds.length,active=(s.rounds||[]).find(r=>r.active),readyRound=active&&(s.readyByRound?.[String(active.n)]||[]).includes(ses.code)?active.n:null,needsRoundPassword=!!active&&active.n>1&&active.passwordRequired!==false&&!s.roundAccess?.[`${active.n}-${ses.code}`];return json({team:t?{name:t.name,code:t.code,points:t.points,progress:t.progress,status:t.status,logo:t.logo,logoColor:t.logoColor,readyRound,needsRoundPassword}:null,state:safeState(s),answers:rows.map(({correct_answer,...a})=>{const roundDone=progress>=Number(a.round_no);return {...a,correct:roundDone?a.correct:null,...(reveal?{correct_answer}: {})}}),revealAnswers:reveal});
 }
 if(m==='POST'&&p==='/api/team/submit-round'){
   const ses=await token(req,env,'team');if(!ses)return fail(401,'Team login required');const b=await body(req),n=Number(b?.round),submitted=Array.isArray(b?.answers)?b.answers:[];if(submitted.length>100)return fail(400,'Too many answers');
   try{const result=await changeState(env,s=>{const r=s.rounds.find(x=>x.n===n),team=s.teams.find(x=>x.code===ses.code);if(!s.running||!r||!r.active||r.deadlineAt&&Date.now()>=r.deadlineAt)throw Object.assign(Error('Round is closed'),{status:409});if(!team)throw Object.assign(Error('Team not found'),{status:404});const progress=Number((team.progress||'0/0').split('/')[0])||0;if(progress!==n-1)throw Object.assign(Error('This round is already locked or not yet available'),{status:409});if(!s.verifiedRounds?.[`${n}-${ses.code}`])throw Object.assign(Error('Enter this round through the team lobby first'),{status:403});const qs=normalizedQuestions(s).filter(q=>q.round===n);if(!qs.length)throw Object.assign(Error('The host has not added questions for this round yet'),{status:409});s.answers=s.answers||[];const byId=new Map(submitted.map(a=>[String(a.questionId),a]));let score=0,elapsed=0;for(const q of qs){const a=byId.get(q.id)||{},answer=String(a.answer||'').slice(0,2000),ok=answer.trim().toLowerCase()===String(q.answer).trim().toLowerCase(),points=ok?Number(q.points??s.points??10):0,ms=Math.max(0,Number(a.elapsedMs)||0);s.answers.push({team_code:ses.code,round_no:n,question_id:q.id,question_text:q.text,answer,correct:ok,correct_answer:q.answer,points,elapsed_ms:ms,submitted_at:new Date().toISOString()});score+=points;elapsed+=ms}s.speedBonus=Number(s.speedBonus)||0;team.points=Number(team.points||0)+score;team.speed=Number(team.speed||0)+elapsed;team.progress=`${Math.min(s.rounds.length,n)}/${s.rounds.length}`;team.status=n>=s.rounds.length?'Complete':`In round ${n+1}`;if(s.teams.every(t=>Number((t.progress||'0/0').split('/')[0])>=n)){r.active=false;r.ended=true;r.status='Completed'}return {ok:true,score,locked:true,progress:team.progress,revealAnswers:team.progress===`${s.rounds.length}/${s.rounds.length}`}});return json(result)}catch(e){if(e.status)return fail(e.status,e.message);throw e}
 }
 if(m==='POST'&&p==='/api/team/answers'){
   const ses=await token(req,env,'team');if(!ses)return fail(401,'Team login required');const b=await body(req);if(!Array.isArray(b?.answers)||b.answers.length>100)return fail(400,'Invalid answer submission');
   const result=await changeState(env,s=>{const r=s.rounds.find(x=>x.n===Number(b.round));if(!s.running||!r||!r.active)throw Object.assign(Error('Round is closed'),{status:409});s.answers=s.answers||[];let score=0,elapsed=0;for(const a of b.answers){if(s.answers.some(x=>x.team_code===ses.code&&x.round_no===r.n&&x.question_id===String(a.questionId)))continue;const q=(s.questions||[]).find(x=>String(x.id)===String(a.questionId)||String(x[0])===String(a.questionId)),expected=q?.answer||q?.[2]||'',ok=String(a.answer||'').trim().toLowerCase()===String(expected).trim().toLowerCase(),pts=ok?Number(q?.points||q?.[4]||s.points||10):0,ms=Math.max(0,Number(a.elapsedMs)||0);s.answers.push({team_code:ses.code,round_no:r.n,question_id:String(a.questionId),answer:String(a.answer||'').slice(0,2000),correct:ok,points:pts,elapsed_ms:ms,submitted_at:new Date().toISOString()});score+=pts;elapsed+=ms}return {ok:true,score,elapsedMs:elapsed,locked:true}});return json(result);
 }
 if(m==='POST'&&p==='/api/team/finish-round'){
   const ses=await token(req,env,'team');if(!ses)return fail(401,'Team login required');const b=await body(req),n=Number(b?.round);
   try{const result=await changeState(env,s=>{const r=s.rounds.find(x=>x.n===n),team=s.teams.find(x=>x.code===ses.code);if(expireRound(s,r))throw Object.assign(Error('Round is closed'),{status:409});if(!s.running||!r||!r.active)throw Object.assign(Error('Round is closed'),{status:409});if(!team)throw Object.assign(Error('Team not found'),{status:404});const count=Number((team.progress||'0/4').split('/')[0])||0;if(count>=r.n)throw Object.assign(Error('This round is already locked'),{status:409});let score=0;s.answers=s.answers||[];const answer=b.answer===undefined?'':String(b.answer).slice(0,2000),q=(s.questions||[]).find(x=>Number(x.round||String(x[0]||'').match(/\d+/)?.[0])===r.n);if(q){const id=String(q.id||1);if(s.answers.some(x=>x.team_code===ses.code&&x.round_no===r.n&&x.question_id===id))throw Object.assign(Error('Your answer is already locked'),{status:409});const ok=answer.trim().toLowerCase()===String(q.answer||q[2]||'').trim().toLowerCase();score=ok?Number(q.points||q[4]||s.points||10):0;s.answers.push({team_code:ses.code,round_no:r.n,question_id:id,answer,correct:ok,points:score,elapsed_ms:Math.max(0,Number(b.elapsedMs)||0),submitted_at:new Date().toISOString()})}team.points=Number(team.points||0)+score;const total=s.rounds.length;team.progress=`${Math.min(total,count+1)}/${total}`;team.status=count+1>=total?'Complete':`In round ${count+2}`;return {ok:true,score,locked:true,progress:team.progress}});return json(result)}catch(e){if(e.status)return fail(e.status,e.message);throw e}
 }
 if(m==='GET'&&p==='/api/admin/export.csv'){
   if(!await token(req,env,'admin'))return fail(401,'Admin login required');const {state:s}=await getState(env),rows=(s.answers||[]).sort((a,b)=>a.round_no-b.round_no||a.team_code.localeCompare(b.team_code)||a.question_id.localeCompare(b.question_id)).map(a=>({...a,team:s.teams.find(t=>t.code===a.team_code)?.name||''})),head='Team,Team login code,Round,Question ID,Question,Submitted answer,Correct answer,Correct,Points,Time (ms),Submitted at';return new Response([head,...rows.map(x=>[x.team,x.team_code,x.round_no,x.question_id,x.question_text,x.answer,x.correct_answer,x.correct?'Yes':'No',x.points,x.elapsed_ms,x.submitted_at].map(csvCell).join(','))].join('\r\n'),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="quiz-master-answers.csv"','cache-control':'no-store'}});
 }
 return fail(404,'Not found');
}

export default { async fetch(request,env){
 try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await handleApi(request,env,url);if(url.pathname.startsWith('/media/')){if(request.method!=='GET')return new Response('Not found',{status:404});const id=url.pathname.slice('/media/'.length);if(!/^[0-9a-f-]{36}$/i.test(id))return new Response('Not found',{status:404});const row=await env.DB.prepare('SELECT mime_type,data FROM question_media WHERE id=?').bind(id).first();if(!row)return new Response('Not found',{status:404});return new Response(row.data,{headers:{'content-type':row.mime_type,'cache-control':'public, max-age=31536000','x-content-type-options':'nosniff'}})}if(!['/','/index.html','/admin','/admin.html','/participant','/participant.html','/audience','/audience.html'].includes(url.pathname))return new Response('Not found',{status:404});return await env.ASSETS.fetch(request)}
 catch(e){console.error(e);return fail(e.status||500,e.status?e.message:'Server error')}
}};
